name: flutter_upchunk
description: A chunk uploader based on the JS library https://github.com/muxinc/upchunk done by MUX, Inc.
version: 1.3.1
homepage: https://github.com/gabrielginter/flutter-upchunk

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.6
  connectivity_plus: ^2.3.7
  mime: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
